DROP TABLE IF EXISTS point_order;
DROP TABLE IF EXISTS point_record;
DROP TABLE IF EXISTS point_product;
DROP TABLE IF EXISTS point_rule;

CREATE TABLE point_rule (
  id VARCHAR(64) PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  rule_type VARCHAR(30) NOT NULL,
  points INT NOT NULL,
  description VARCHAR(255),
  status TINYINT NOT NULL DEFAULT 1,
  is_del TINYINT NOT NULL DEFAULT 0,
  create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE point_record (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  rule_type VARCHAR(30),
  points INT NOT NULL,
  balance INT NOT NULL,
  source_id VARCHAR(64),
  source_type VARCHAR(30),
  remark VARCHAR(255),
  create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE point_product (
  id VARCHAR(64) PRIMARY KEY,
  name VARCHAR(200) NOT NULL,
  description CLOB,
  image_url VARCHAR(500),
  points_price INT NOT NULL,
  stock INT NOT NULL DEFAULT 0,
  status TINYINT NOT NULL DEFAULT 1,
  sort INT NOT NULL DEFAULT 0,
  is_del TINYINT NOT NULL DEFAULT 0,
  create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE point_order (
  id VARCHAR(64) PRIMARY KEY,
  user_id BIGINT NOT NULL,
  product_id VARCHAR(64) NOT NULL,
  product_name VARCHAR(200) NOT NULL,
  points_price INT NOT NULL,
  quantity INT NOT NULL DEFAULT 1,
  total_points INT NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
  address VARCHAR(500),
  remark VARCHAR(255),
  create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX uk_point_rule_type ON point_rule(rule_type);
CREATE INDEX idx_point_record_user_id ON point_record(user_id);
CREATE INDEX idx_point_record_create_time ON point_record(create_time);
CREATE INDEX idx_point_product_sort ON point_product(sort);
CREATE INDEX idx_point_order_user_id ON point_order(user_id);

