CREATE TABLE `edu_exam_record` (
  `id` VARCHAR(64) NOT NULL COMMENT '雪花ID',
  `exam_id` VARCHAR(64) NOT NULL COMMENT '考试ID',
  `paper_id` VARCHAR(64) NOT NULL COMMENT '试卷快照ID',
  `user_id` BIGINT NOT NULL COMMENT '考生ID',
  `dept_id` BIGINT NOT NULL DEFAULT 0 COMMENT '部门ID',
  `total_score` INT NOT NULL DEFAULT 0 COMMENT '试卷总分',
  `obtain_score` INT NOT NULL DEFAULT 0 COMMENT '获得分数',
  `status` TINYINT NOT NULL DEFAULT 1 COMMENT '状态：1-进行中 2-已提交 3-已评分',
  `start_time` DATETIME(3) NOT NULL COMMENT '开始时间',
  `submit_time` DATETIME(3) DEFAULT NULL COMMENT '提交时间',
  `ip_address` VARCHAR(50) DEFAULT NULL COMMENT '考试IP',
  `switch_count` INT NOT NULL DEFAULT 0 COMMENT '切屏次数',
  `answers` JSON DEFAULT NULL COMMENT '考生答案JSON',
  `create_by` BIGINT NOT NULL DEFAULT 0 COMMENT '创建人',
  `create_time` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  `update_by` BIGINT NOT NULL DEFAULT 0 COMMENT '更新人',
  `update_time` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
  `is_deleted` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除：0-否 1-是',
  PRIMARY KEY (`id`),
  KEY `idx_record_exam_id` (`exam_id`),
  KEY `idx_record_user_id` (`user_id`),
  KEY `idx_record_dept_id` (`dept_id`),
  KEY `idx_record_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='考试记录表';

CREATE TABLE `edu_exam_session` (
  `id` VARCHAR(64) NOT NULL COMMENT '雪花ID',
  `record_id` VARCHAR(64) NOT NULL COMMENT '考试记录ID',
  `exam_id` VARCHAR(64) NOT NULL COMMENT '考试ID',
  `paper_id` VARCHAR(64) NOT NULL COMMENT '试卷ID',
  `user_id` BIGINT NOT NULL COMMENT '考生ID',
  `status` TINYINT NOT NULL DEFAULT 1 COMMENT '状态：1-进行中 2-已提交 3-已超时',
  `start_time` DATETIME(3) NOT NULL COMMENT '开始时间',
  `end_time` DATETIME(3) NOT NULL COMMENT '结束时间',
  `submit_time` DATETIME(3) DEFAULT NULL COMMENT '提交时间',
  `last_active_time` DATETIME(3) DEFAULT NULL COMMENT '最后活跃时间',
  `ip_address` VARCHAR(50) DEFAULT NULL COMMENT '考试IP',
  `create_by` BIGINT NOT NULL DEFAULT 0 COMMENT '创建人',
  `create_time` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  `update_by` BIGINT NOT NULL DEFAULT 0 COMMENT '更新人',
  `update_time` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
  `is_deleted` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除：0-否 1-是',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_exam_session_record_id` (`record_id`),
  KEY `idx_session_exam_id` (`exam_id`),
  KEY `idx_session_user_id` (`user_id`),
  KEY `idx_session_status` (`status`),
  KEY `idx_session_end_time` (`end_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='考试会话表';
